from selenium import webdriver
from selenium.webdriver import DesiredCapabilities
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from datetime import datetime
from time import sleep
from csv import writer
import pandas as pd
import pycountry
import requests
import getpass
import gspread
import pytz
import math
import time
import json
import os
import re

# 		["Abilene, TX",
# 		"Aiken, SC",
# 		"Akron, OH",
# 		"Alameda, CA",
# 		"Albany, GA",
# 		"Albany, NY",
# 		"Albuquerque, NM",
# 		"Alexandria, LA",
# 		"Alexandria, VA",
# 		"Alhambra, CA",
# 		"Allen, TX",
# 		"Allentown, PA",
# 		"Alpharetta, GA",
# 		"Altoona, PA",
# 		"Amarillo, TX",
# 		"Ames, IA",
# 		"AMHERST, MA",
# 		"Amherst, NY",
# 		"Anaheim, CA",
# 		"Anchorage, AK",
# 		"Anderson, SC",
# 		"Ankeny, IA",
# 		"Ann Arbor, MI",
# 		"Annandale, VA",
# 		"Annapolis, MD",
# 		"Apex, NC",
# 		"APO, AE",
# 		"APO, AP",
# 		"Appleton, WI",
# 		"Arcadia, CA",
# 		"Arkadelphia, AR",
# 		"Arlington Heights, IL",
# 		"Arlington, MA",
# 		"Arlington, TX",
# 		"Arlington, VA",
# 		"Arvada, CO",
# 		"Ashburn, VA",
# 		"Asheville, NC",
# 		"Astoria, NY",
# 		"Athens, GA",
# 		"Athens, OH",
# 		"Atlanta, GA",
# 		"Auburn, AL",
# 		"AUGUSTA, GA",
# 		"Augusta, ME",
# 		"Aurora, CO",
# 		"Aurora, IL",
# 		"Austin, TX",
# 		"BAKERSFIELD, CA",
# 		"Ballwin, MO",
# 		"Baltimore, MD",
# 		"Bangor, ME",
# 		"Baton Rouge, LA",
# 		"Battle Creek, MI",
# 		"Bayamon, PR",
#		"Bayside, NY",
#		"Beachwood, OH",
#		"Beaumont, TX",
#		"Beavercreek, OH",
#		"Beaverton, OR",
#		"Bedford, TX",
#		"beijing, B",
#		"Bel Air, MD",
#		"Bellevue, WA",
#		"Bellingham, WA",
#		"Bend, OR",
#		"Benton, AR",
#		"Berkeley, CA",
#		"Berrien Springs, MI",
#		"Bethesda, MD",
#		"Bethlehem, PA",
#		"Beverly Hills, CA",
#		"Beverly, MA",
#		"Billings, MT",
#		"Biloxi, MS",
#		"Binghamton, NY",
#		"Birmingham, AL",
#		"Bismarck, ND",
#		"Blacksburg, VA",
#		"Bloomfield Hills, MI",
#		"Bloomington, IL",
#		"Bloomington, IN",
#		"Bloomington, MN",
#		"Bluffton, OH",
#		"Boca Raton, FL",
#		"Boise, ID",
#		"Bolingbrook, IL",
		# "Boone, NC",
		# "Boston, MA",
		# "Bothell, WA",
		# "Boulder, CO",
		# "Bourbonnais, IL",
		# "Bowie, MD",
		# "Bowling Green, KY",
		# "Bowling Green, OH",
		# "Boynton Beach, FL",
		# "Bozeman, MT",
		# "Bradenton, FL",
		# "Brandon, FL",
		# "Brandon, MS",
		# "Bremerton, WA",
		# "Brentwood, TN",
		# "BRIDGEPORT, CT",
		# "Bridgewater, NJ",
		# "Brighton, MA",
		# "Brighton, MI",
		# "Broken Arrow, OK",
		# "Bronx, NY",
		# "Brookfield, WI",
		# "Brookings, SD",
		# "brookline, MA",
		# "Brooklyn, NY",
		# "Broomfield, CO",
		# "Bryan, TX",
		# "Bryn Mawr, PA",
		# "Buffalo Grove, IL",
		# "Buffalo, NY",
		# "Burbank, CA",
		# "Burlingame, CA",
		# "Burlington, VT",
		# "Burnsville, MN",
		# "Caguas , PR",
		# "Calgary, AB",
		# "Camarillo, CA",
		# "Cambridge, MA",
		# "Camp Hill, PA",
		# "Canfield, OH",
		# "Canton, MI",
		# "Canton, OH",
		# "Cape Coral, FL",
		# "Cape Girardeau, MO",
		# "Carbondale, IL",
		# "Carlisle, PA",
		# "Carlsbad, CA",
		# "carmel, IN",
		# "Carmichael, CA",
		# "Carolina, PR",
		# "Carrboro, NC",
		# "Carrollton, TX",
		# "Carson city, NV",
		# "Cary, NC",
		# "Casper, WY",
		# "Castle Rock, CO",
		# "Castro Valley, CA",
		# "Cedar Park, TX",
		# "Cedar Rapids, IA",
		# "Centennial, CO",
		# "Centerville, OH",
		# "Champaign, IL",
		# "Chandler, AZ",
		# "Chapel Hill, NC",
		# "Charleston, IL",
		# "Charleston, SC",
		# "Charleston, WV",
		# "Charlotte, NC",
		# "Charlottesville, VA",
		# "Chattanooga, TN",
		# "Cherry Hill, NJ",
		# "Chesapeake, VA",
		# "Chesterfield, MO",
		# "Cheyenne, WY",
		# "Chicago, IL",
		# "Chico, CA",
		# "CHINO HILLS, CA",
		# "Chula Vista, CA",
		# "Cincinnati, OH",
		# "Claremont, CA",
		# "Clarks Summit, PA",
		# "Clarksville, TN",
		# "Clearwater, FL",
		# "Clemson, SC",
		# "Cleveland Heights, OH",
		# "Cleveland, OH",
		# "Clifton, NJ",
		# "Clovis, CA",
		# "Coeur D Alene, ID",
		# "College Park, MD",
		# "College Station, TX",
		# "Collierville, TN",
		# "Colorado Springs, CO",
		# "Colton, CA",
		# "Columbia, MD",
		# "Columbia, MO",
		# "Columbia, SC",
		# "Columbus, GA",
		# "Columbus, OH",
		# "Concord, CA",
		# "Concord, NH",
		# "Conroe, TX",
		# "Conway, AR",
		# "Cookeville, TN",
		# "Coppell, TX",
		# "Coral Gables, FL",
		# "Coral Springs, FL",
		# "Cordova, TN",
		# "Corona, CA",
		# "Corpus christi, TX",
		# "Corvallis, OR",
		# "Costa Mesa, CA",
		# "Covington, LA",
		# "Cranston, RI",
		# "Crown Point, IN",
		# "Crystal Lake, IL",
		# "Cullowhee, NC",
		# "Cumberland, MD",
		# "Cumming, GA",
		# "Cuyahoga Falls, OH",
		# "Cypress, TX",
		# "Dallas, PA",
		# "Dallas, TX",
		# "Daly City, CA",
		# "Danbury, CT",
		# "Danville, CA",
		# "Danville, PA",
		# "Darien, IL",
		# "Davenport, IA",
		# "Davie, FL",
		# "Davis, CA",
		# "Dayton, OH",
		# "De Pere, WI",
		# "Dearborn, MI",
		# "Decatur, GA",
		# "Decatur, IL",
		# "Deerfield, IL",
		# "DeKalb, IL",
		# "Delray Beach, FL",
		# "Denton, TX",
		# "Denver, CO",
		# "Des Moines, IA",
		# "DES PLAINES, IL",
		# "Detroit, MI",
		# "Diamond Bar, CA",
		# "Doral, FL",
		# "Dorchester, MA",
		# "Dothan, AL",
		# "Dover, DE",
		# "Dover, NH",
		# "Downers Grove, IL",
		# "Downey, CA",
		# "Downingtown, PA",
		# "Doylestown, PA",
		# "Dubai, UAE",
		# "Dublin, OH",
		# "Duluth, GA",
		# "Duluth, MN",
		# "Durango, CO",
		# "Durham, NC",
		# "Durham, NH",
		# "Eagan, MN",
		# "East Brunswick, NJ",
		# "East Lansing, MI",
		# "East Meadow, NY",
		# "Easton, PA",
		# "Eau Claire, WI",
		# "Eden Prairie, MN",
		# "Edina, MN",
		# "Edinburg, TX",
		# "Edison, NJ",
		# "Edmond, OK",
		# "Edmonds, WA",
		# "Edmonton, AB",
		# "El Cajon, CA",
		# "El Paso, TX",
		# "Elgin, IL",
		# "Elk Grove Village, IL",
		# "Elk Grove, CA",
		# "Ellensburg, WA",
		# "Ellicott City, MD",
		# "Elmhurst, IL",
		#"encinitas, CA",
		# "Encino, CA",
		# "Englewood, CO",
		# "Erie, PA",
		# "Escondido, CA",
		# "Eugene, OR",
		# "Evanston, IL",
		# "EVANSVILLE, IN",
		# "Everett, WA",
		# "Fairfax, VA",
		# "Fairfield, CA",
		# "Fairfield, CT",
		# "Fairport, NY",
		# "Falls Church, VA",
		# "Fargo, ND",
		# "Farmington Hills, MI",
		# "Farmington, CT",
		# "Fayetteville, AR",
		# "Fayetteville, GA",
		# "Fayetteville, NC",
		# "Findlay, OH",
		# "Fishers, IN",
		# "Flagstaff, AZ",
		# "Flemington, NJ",
		# "Florence, SC",
		# "Florissant, MO",
		# "Flower Mound, TX",
		# "Flushing, NY",
		# "Folsom, CA",
		# "Fontana, CA",
		# "Forest Hills, NY",
		# "Fort Collins, CO",
		# "Fort Lauderdale, FL",
		# "Fort Mill, SC",
		# "Fort Myers, FL",
		# "Fort Smith, AR",
		# "Fort Wayne, IN",
		# "Fort Worth, TX",
		# "Fountain Valley, CA",
		# "FPO, AP",
		# "Framingham, MA",
		# "Frankfort, KY",
		# "Franklin, TN",
		# "Frederick , MD",
		# "Fredericksburg, VA",
		# "Freehold, NJ",
		# "FREMONT, CA",
		# "Fresno, CA",
		# "Frisco, TX",
		# "Fullerton, CA",
		# "Gainesville, FL",
		# "Gainesville, GA",
		# "Gaithersburg, MD",
cities = ["Galveston, TX",
		"Garland, TX",
		"Gastonia, NC",
		"Geneva, IL",
		"Georgetown, TX",
		"Germantown, TN",
		"Gig Harbor, WA",
		"Gilbert, AZ",
		"Glastonbury, CT",
		"Glen Allen, VA",
		"Glen Ellyn, IL",
		"Glendale, AZ",
		"Glendale, CA",
		"Glenview, IL",
		"Golden, CO",
		"Goldsboro, NC",
		"Goodyear, AZ",
		"Goshen, IN",
		"Grand Forks, ND",
		"Grand Junction, CO",
		"Grand Prairie, TX",
		"Grand Rapids, MI",
		"Great Falls, MT",
		"Great Neck, NY",
		"Greeley, CO",
		"Green Bay, WI",
		"Greensboro, NC",
		"Greensburg, PA",
		"Greenville, NC",
		"Greenville, SC",
		"Greenwich, CT",
		"Greenwood, IN",
		"Greer, SC",
		"Guaynabo, PR",
		"Gulfport, MS",
		"Halifax, NS",
		"Hamden, CT",
		"Hamilton, OH",
		"Hammond, LA",
		"Hampton, VA",
		"Harlingen, TX",
		"Harrisburg, PA",
		"Harrisonburg, VA",
		"Hartford, CT",
		"Hattiesburg, MS",
		"Hayward, CA",
		"Helena, MT",
		"Henderson, NV",
		"Hendersonville, NC",
		"Hendersonville, TN",
		"Herndon, VA",
		"Hershey, PA",
		"Hialeah, FL",
		"Hickory, NC",
		"High Point, NC",
		"Highland, CA",
		"Highlands Ranch, CO",
		"Hilliard, OH",
		"Hillsborough, NJ",
		"Hinsdale, IL",
		"Hoboken, NJ"]
		# "Hoffman Estates, IL",
		# "Holland, MI",
		# "Hollywood, FL",
		# "Honolulu, HI",
		# "Hoover, AL",
		# "Houma, LA",
		# "Houston, TX",
		# "Hudson, OH",
		# "Humble, TX",
		# "Huntersville, NC",
		# "Huntington Beach, CA",
		# "Huntington, NY",
		# "Huntington, WV",
		# "Huntsville, AL",
		# "Huntsville, TX",
		# "Hutchinson, KS",
		# "Idaho Falls, ID",
		# "Indiana, PA",
		# "Indianapolis, IN",
		# "Iowa City, IA",
		# "Irvine, CA",
		# "irving, TX",
		# "Issaquah, WA",
		# "Ithaca, NY",
		# "Jackson , TN",
		# "Jackson, MI",
		# "jackson, MS",
		# "Jacksonville, FL",
		# "Jacksonville, NC",
		# "jamaica plain, MA",
		# "Jamaica, NY",
		# "Janesville, WI",
		# "Jefferson City, MO",
		# "Jersey City, NJ",
		# "Johnson City, TN",
		# "Johnstown, PA",
		# "Jonesboro, AR",
		# "Juneau, AK",
		# "Jupiter, FL",
		# "Kailua, HI",
		# "Kalamazoo, MI",
		# "Kalispell, MT",
		# "Kansas City, KS",
		# "Kansas City, MO",
		# "Katy, TX",
		# "Keene, NH",
		# "Keller, TX",
		# "Kenmore, WA",
		# "Kenner, LA",
		# "Kennesaw, GA",
		# "Kennewick, WA",
		# "Kenosha, WI",
		# "Kent, OH",
		# "Kent, WA",
		# "Kettering, OH",
		# "Kingsport, TN",
		# "Kingston, RI",
		# "Kingwood, TX",
		# "Kirkland, WA",
		# "Kissimmee, FL",
		# "Knoxville, TN",
		# "La Crosse, WI",
		# "La Jolla, CA",
		# "La Mesa, CA",
		# "Lafayette, IN",
		# "Lafayette, LA",
		# "Laguna Niguel, CA",
		# "Lake Charles, LA",
		# "LAKE OSWEGO, OR",
		# "Lake Worth, FL",
		# "Lakeland, FL",
		# "Lakeville, MN",
		# "Lakewood, CA",
		# "Lakewood, CO",
		# "LAKEWOOD, NJ",
		# "Lakewood, OH",
		# "Lancaster, CA",
		# "Lancaster, NY",
		# "Lancaster, PA",
		# "Langhorne, PA",
		# "Lansdale, PA",
		# "Lansing, MI",
		# "Laramie, WY",
		# "Laredo, TX",
		# "Largo, FL",
		# "Las Cruces, NM",
		# "Las Vegas, NV",
		# "Laurel, MD",
		# "Lawrence, KS",
		# "Lawrenceville, GA",
		# "League City, TX",
		# "Lees Summit, MO",
		# "Leesburg, VA",
		# "Lenexa, KS",
		# "Lewiston, ME",
		# "Lewisville, TX",
		# "Lexington, KY",
		# "Lexington, SC",
		# "Lima, OH",
		# "Lincoln, NE",
		# "Lisle, IL",
		# "Little Rock, AR",
		# "Littleton, CO",
		# "Livermore, CA",
		# "Liverpool, NY",
		# "Livingston, NJ",
		# "Livonia, MI",
		# "Logan, UT",
		# "Loma Linda, CA",
		# "Lombard, IL",
		# "London, ON",
		# "Long Beach, CA",
		# "Long Island City, NY",
		# "Longmont, CO",
		# "Longview, TX",
		# "Los Altos, CA",
		# "Los Angeles, CA",
		# "Los Gatos, CA",
		# "Louisville, KY",
		# "Loveland, CO",
		# "Loveland, OH",
		# "Lubbock, TX",
		# "Lufkin, TX",
		# "Lynchburg, VA",
		# "Lynnwood, WA",
		# "Macomb, IL",
		# "Macon, GA",
		# "Madera, CA",
		# "Madison, AL",
		# "Madison, MS",
		# "Madison, WI",
		# "Manalapan, NJ",
		# "Manassas, VA",
		# "Manchester , CT",
		# "Manchester, NH",
		# "Mandeville, LA",
		# "Manhattan, KS",
		# "Manitowoc, WI",
		# "Mankato, MN",
		# "Maple Grove, MN",
		# "Marietta, GA",
		# "Marlton, NJ",
		# "Marquette, MI",
		# "Marshfield, WI",
		# "Martin, TN",
		# "Martinez, CA",
		# "Maryville, MO",
		# "Maryville, TN",
		# "Mason, OH",
		# "Massillon, OH",
		# "Matthews, NC",
		# "McAllen, TX",
		# "Mckinney, TX",
		# "Mechanicsburg, PA",
		# "Medford, MA",
		# "Medford, OR",
		# "Media, PA",
		# "Medina, OH",
		# "Melbourne, FL",
		# "Memphis, TN",
		# "Menlo Park, CA",
		# "Menomonee Falls, WI",
		# "Menomonie, WI",
		# "Mentor, OH",
		# "Merced, CA",
		# "Meridian, ID",
		# "Meridian, MS",
		# "Mesa, AZ",
		# "METAIRIE, LA",
		# "Miami Beach, FL",
		# "Miami, FL",
		# "Miamisburg, OH",
		# "Middletown, CT",
		# "Midland, MI",
		# "Midland, TX",
		# "Midlothian, VA",
		# "Milford, CT",
		# "Milwaukee, WI",
		# "Minneapolis, MN",
		# "Minnetonka, MN",
		# "Minot, ND",
		# "Miramar, FL",
		# "Mishawaka, IN",
		# "Mission Viejo, CA",
		# "Mission, TX",
		# "Mississauga, ON",
		# "Missoula, MT",
		# "Missouri City, TX",
		# "Mobile, AL",
		# "Modesto, CA",
		# "Monroe, LA",
		# "Montclair, NJ",
		# "Monterey park , CA",
		# "Monterey, CA",
		# "Montgomery, AL",
		# "Montreal, QC",
		# "Mooresville, NC",
		# "Moorhead, MN",
		# "Moreno Valley, CA",
		# "Morgantown, WV",
		# "MORRISTOWN, NJ",
		# "Moscow, ID",
		# "Mount Pleasant, MI",
		# "Mount Pleasant, SC",
		# "Mountain View, CA",
		# "Muncie, IN",
		# "Murfreesboro, TN",
		# "Murray, KY",
		# "Murrieta, CA",
		# "Muskegon, MI",
		# "Muskogee, OK",
		# "Myrtle Beach, SC",
		# "Nacogdoches, TX",
		# "Napa, CA",
		# "Naperville, IL",
		# "Naples, FL",
		# "Nashua, NH",
		# "Nashville, TN",
		# "Natick, MA",
		# "Needham, MA",
		# "New Bern, NC",
		# "New Braunfels, TX",
		# "New Brunswick, NJ",
		# "New haven, CT",
		# "New Hyde Park, NY",
		# "New Orleans, LA",
		# "New Rochelle, NY",
		# "New York, NY",
		# "Newark, DE",
		# "Newark, NJ",
		# "Newport Beach, CA",
		# "Newport News, VA",
		# "Newton, MA",
		# "Newtown, PA",
		# "Noblesville, IN",
		# "Norfolk , VA",
		# "Normal, IL",
		# "Norman, OK",
		# "North Canton, OH",
		# "North Las Vegas, NV",
		# "North Little Rock, AR",
		# "Northbrook, IL",
		# "Northport, AL",
		# "Northridge, CA",
		# "Northville, MI",
		# "Norwalk, CT",
		# "Novato, CA",
		# "Novi, MI",
		# "Oak Park, IL",
		# "Oakland, CA",
		# "Ocala, FL",
		# "Oceanside, CA",
		# "Oconomowoc, WI",
		# "Ogden, UT",
		# "Oklahoma City, OK",
		# "Olathe, KS",
		# "Olympia, WA",
		# "Omaha, NE",
		# "Oneonta, NY",
		# "Ontario, CA",
		# "Orange Park, FL",
		# "Orange, CA",
		# "Orem, UT",
		# "Orland Park, IL",
		# "Orlando, FL",
		# "Oshkosh, WI",
		# "Ottawa, ON",
		# "Overland Park, KS",
		# "Owensboro, KY",
		# "oxford, MS",
		# "oxford, OH",
		# "Oxnard, CA",
		# "Paducah, KY",
		# "Palatine, IL",
		# "Palm Beach Gardens, FL",
		# "Palm Harbor, FL",
		# "Palm Springs, CA",
		# "Palo Alto, CA",
		# "Panama City, FL",
		# "Park Ridge, IL",
		# "Parker, CO",
		# "Parma, OH",
		# "Pasadena, CA",
		# "Pasadena, TX",
		# "Pearland, TX",
		# "Pembroke Pines, FL",
		# "Pensacola, FL",
		# "Peoria, AZ",
		# "Peoria, IL",
		# "Perrysburg, OH",
		# "Petaluma, CA",
		# "Petersburg, VA",
		# "Philadelphia, PA",
		# "Phoenix, AZ",
		# "Phoenixville, PA",###################################
		# "Pine Bluff, AR",
		# "Piscataway, NJ",
		# "Pittsburgh, PA",
		# "Pittsford, NY",
		# "Plainfield, IL",
		# "Plano, TX",
		# "Plantation, FL",
		# "Plattsburgh, NY",
		# "Pleasanton, CA",
		# "Plymouth, MI",
		# "Plymouth, MN",
		# "Pocatello, ID",
		# "Pomona, CA",
		# "Port Charlotte, FL",
		# "Port Saint Lucie, FL",
		# "Portage, MI",
		# "Portland, ME",
		# "Portland, OR",
		# "Portsmouth, NH",
		# "Portsmouth, VA",
		# "Potomac, MD",
		# "Poughkeepsie, NY",
		# "Poway, CA",
		# "Powell, OH",
		# "PRESCOTT, AZ",
		# "Princeton, NJ",
		# "Providence, RI",
		# "Provo, UT",
		# "Pueblo, CO",
		# "Pullman, WA",
		# "Puyallup, WA",
		# "Quincy, IL",
		# "Quincy, MA",
		# "Radford, VA",
		# "Raleigh, NC",
		# "Rancho Cucamonga, CA",
		# "Rapid City, SD",
		# "Reading, PA",
		# "Redding, CA",
		# "Redlands, CA",
		# "Redmond , WA",
		# "Redondo Beach, CA",
		# "Redwood City, CA",
		# "Reno, NV",
		# "Renton, WA",
		# "Reston, VA",
		# "Richardson, TX",
		# "Richland, WA",
		# "Richmond, KY",
		# "richmond, TX",
		# "Richmond, VA",
		# "Ridgewood, NJ",
		# "River Forest, IL",
		# "Riverside, CA",
		# "Riverview, FL",
		# "Riyadh, Riyadh",
		# "Roanoke, VA",
		# "Rochester Hills, MI",
		# "Rochester, MN",
		# "Rochester, NY",
		# "Rock Hill, SC",
		# "Rockford, IL",
		# "Rockville, MD",
		# "Roseville, CA",
		# "Roseville, MN",
		# "Roswell, GA",
		# "Round Rock, TX",
		# "Royal Oak, MI",
		# "Ruston, LA",
		# "Sacramento, CA",
		# "Saginaw, MI",
		# "Saint Augustine, FL",
		# "Saint Charles, MO",
		# "Saint Cloud, MN",
		# "Saint Louis, MO",
		# "Saint Paul, MN",
		# "Saint Petersburg, FL",
		# "Salem, MA",
		# "Salem, OR",
		# "Salinas, CA",
		# "Salisbury, MD",
		# "Salisbury, NC",
		# "Salt Lake City, UT",
		# "San Angelo, TX",
		# "San Antonio, TX",
		# "San Bernardino, CA",
		# "San Diego, CA",
		# "San Francisco, CA",
		# "San Gabriel, CA",
		# "San Jose, CA",
		# "San Juan, PR",
		# "San Leandro, CA",
		# "San Luis Obispo, CA",
		# "San Marcos, CA",
		# "San Marcos, TX",
		# "San Mateo, CA",
		# "San Rafael, CA",
		# "San Ramon, CA",
		# "Sandy, UT",
		# "Santa Ana, CA",
		# "Santa Barbara, CA",
		# "Santa Clara, CA",
		# "Santa Cruz, CA",
		# "Santa Fe, NM",
		# "Santa Maria, CA",
		# "Santa Monica, CA",
		# "Santa Rosa, CA",
		# "Sarasota, FL",
		# "Saratoga Springs, NY",
		# "Saskatoon, SK",
		# "Savannah, GA",
		# "Scarsdale, NY",
		# "Schaumburg, IL",
		# "Schenectady, NY",
		# "Scottsdale, AZ",
		# "Scranton, PA",
		# "Searcy, AR",
		# "Seattle, WA",
		# "Sewell, NJ",
		# "Shakopee, MN",
		# "Shawnee Mission, KS",
		# "Shawnee, KS",
		# "Sherman Oaks, CA",
		# "Shoreline, WA",
		# "Shreveport, LA",
		# "Silver Spring, MD",
		# "Simi Valley, CA",
		# "Simpsonville, SC",
		# "Singapore, Singapore",
		# "Sioux City, IA",
		# "Sioux Falls, SD",
		# "Skokie, IL",
		# "Slidell, LA",
		# "Smithtown, NY",
		# "Smyrna, GA",
		# "Solon, OH",
		# "Somerset, KY",
		# "Somerville, MA",
		# "South bend, IN",
		# "South Portland, ME",
		# "Southfield, MI",
		# "Southlake, TX",
		# "Sparks , NV",
		# "Spartanburg, SC",
		# "Spokane, WA",
		# "Spring, TX",
		# "Springdale, AR",
		# "Springfield, IL",
		# "Springfield, MA",
		# "Springfield, MO",
		# "Springfield, OH",
		# "Springfield, OR",
		# "Springfield, VA",
		# "St Louis, MO",
		# "St Paul, MN",
		# "St Petersburg, FL",
		# "St. Louis, MO",
		# "St. Paul, MN",
		# "St. Petersburg, FL",
		# "Stamford, CT",
		# "Starkville, MS",
		# "State College, PA",
		# "Staten Island, NY",
		# "Statesboro, GA",
		# "Sterling Heights, MI",
		# "Stevens Point, WI",
		# "Stillwater, OK",
		# "Stockton, CA",
		# "Storrs, CT",
		# "Stow, OH",
		# "Strongsville, OH",
		# "Stuart, FL",
		# "Sugar Land, TX",
		# "Summerville, SC",
		# "Sunnyvale, CA",
		# "Surprise, AZ",
		# "Suwanee, GA",
		# "Sylvania, OH",
		# "Syracuse, NY",
		# "Tacoma, WA",
		# "Tahlequah, OK",
		# "Tallahassee, FL",
		# "Tampa, FL",
		# "teaneck, NJ",
		# "Temecula, CA",
		# "Tempe, AZ",
		# "Temple, TX",
		# "Terre Haute, IN",
		# "Texarkana, TX",
		# "The Woodlands, TX",
		# "Thibodaux, LA",
		# "Thornton, CO",
		# "Thousand Oaks, CA",
		# "Toledo, OH",
		# "Tomball, TX",
		# "Toms River, NJ",
		# "Tonawanda, NY",
		# "Topeka, KS",
		# "Toronto, ON",
		# "Torrance, CA",
		# "Towson, MD",
		# "Traverse City, MI",
		# "Trenton, NJ",
		# "Troy, MI",
		# "Troy, NY",
		# "Trujillo Alto, PR",
		# "Tucson, AZ",
		# "Tulsa, OK",
		# "Tupelo, MS",
		# "Tuscaloosa, AL",
		# "Tyler, TX",
		# "University Park, PA",
		# "University, MS",
		# "Upland, CA",
		# "Urbana, IL",
		# "Urbandale, IA",
		# "Utica, NY",
		# "Vacaville, CA",
		# "Valencia, CA",
		# "Valley Stream, NY",
		# "Valparaiso, IN",
		# "van nuys, CA",
		# "Vancouver, BC",
		# "Vancouver, WA",
		# "Ventura, CA",
		# "Vero Beach, FL",
		# "VICTORIA, TX",
		# "Vienna, VA",
		# "Virginia Beach, VA",
		# "VISALIA, CA",
		# "Vista, CA",
		# "Voorhees, NJ",
		# "Waco, TX",
		# "Wallingford, CT",
		# "Walnut Creek, CA",
		# "Walnut, CA",
		# "Waltham, MA",
		# "Warren, OH",
		# "Warrensburg, MO",
		# "Warwick, RI",
		# "Washington, DC",
		# "Waterloo, IA",
		# "Waukegan, IL",
		# "Waukesha, WI",
		# "Wausau, WI",
		# "Wauwatosa, WI",
		# "Wayne, NJ",
		# "Wellington, FL",
		# "Wenatchee, WA",
		# "West Bloomfield, MI",
		# "West Chester, OH",
		# "West Chester, PA",
		# "West Covina, CA",
		# "West Des Moines, IA",
		# "West Hartford, CT",
		# "West Haven, CT",
		# "West Hills, CA",
		# "West Lafayette, IN",
		# "West Palm Beach, FL",
		# "Westerville, OH",
		# "Westlake Village, CA",
		# "Westlake, OH",
		# "Westminster, CO",
		# "Westminster, MD",
		# "Westmont, IL",
		# "Weston, FL",
		# "Wheaton, IL",
		# "White Plains, NY",
		# "Whittier, CA",
		# "Wichita Falls, TX",
		# "Wichita, KS",
		# "Williamsburg, VA",
		# "Williamsport, PA",
		# "Williamsville, NY",
		# "Wilmington, DE",
		# "Wilmington, NC",
		# "Winchester, VA",
		# "Winnipeg, MB",
		# "Winston Salem, NC",
		# "Winston-Salem, NC",
		# "Winter Park, FL",
		# "Woodbridge, VA",
		# "Woodbury, MN",
		# "Woodland Hills, CA",
		# "Woodland, CA",
		# "Woodstock, GA",
		# "Wooster, OH",
		# "Worcester, MA",
		# "Yakima, WA",
		# "Yonkers, NY",
		# "yorba linda, CA",
		# "YORK, PA",
		# "Youngstown, OH",
		# "ypsilanti, MI",
		# "Yuma, AZ",
		# "Zionsville, IN"]

# cities = ['Abilene, TX']

def append_list_as_row(file_name, list_of_elem):
	with open(file_name, 'a+', newline='', encoding='utf-8') as write_obj:
		csv_writer = writer(write_obj)
		csv_writer.writerow(list_of_elem)

options = Options()
options.add_argument("--headless")
options.add_argument('--no-sandbox')
options.add_argument('--disable-gpu')
options.add_argument('start-maximized')
options.add_argument('disable-infobars')
options.add_argument("--disable-extensions")

filepathHeaderCSV = 'eatright-1.csv'
fHeaderCSV = ['Name', 'Office', 'City', 'Phone', 'Email', 'Website', 'Specialties']

try:
	os.remove(filepathHeaderCSV)
	time.sleep(1)
except Exception as e:
	pass
append_list_as_row(filepathHeaderCSV, fHeaderCSV)

err = 0
while err == 0:
	try:
		driver = webdriver.Chrome(options=options, service = Service(ChromeDriverManager().install()))
		driver.implicitly_wait(20)
		err = 1
	except Exception:
		err = 0
		time.sleep(5)

# CACHE
driver.get('https://www.eatright.org/')
driver.implicitly_wait(60)
time.sleep(3)
driver.find_element(By.CLASS_NAME, 'agree').click()
time.sleep(2)

for city in cities:
	tot = 1
	totPage = str(cities.index(city)+1)+'/'+str(len(cities))+' - '+city

	driver.get('https://www.eatright.org/find-a-nutrition-expert-results?type=in-person&city='+city)
	driver.implicitly_wait(60)
	time.sleep(10)

	if 'Sorry' in driver.find_element(By.TAG_NAME, 'main').get_attribute('innerHTML'):
		print('No Data')
		nextPage = 1
	elif 'fane-search' in driver.find_element(By.TAG_NAME, 'main').get_attribute('innerHTML'):
		Select(driver.find_element(By.ID, 'fane-results-per-page')).select_by_value('24')
		time.sleep(8)

		nextPage = 0
		while nextPage == 0:
			try:
				lists = driver.find_elements(By.CLASS_NAME, 'fane-results-card')
				for l in lists:
					name, office, phone, email, website, specialties = '','','','','',''

					if 'fane-results-card__name' in l.get_attribute('innerHTML'):
						name = l.find_element(By.CLASS_NAME, 'fane-results-card__name').text

					if 'fane-results-card__address' in l.get_attribute('innerHTML'):
						office = l.find_element(By.CLASS_NAME, 'fane-results-card__address').text.replace('\n',', ')

					if 'fane-results-card__phone' in l.get_attribute('innerHTML'):
						p = l.find_element(By.CLASS_NAME, 'fane-results-card__phone').text
						phone = re.sub('\D', '', p)

					if 'fane-results-card__email' in l.get_attribute('innerHTML'):
						email = l.find_element(By.CLASS_NAME, 'fane-results-card__email').text

					if 'fane-results-card__website' in l.get_attribute('innerHTML'):
						website = l.find_element(By.CLASS_NAME, 'fane-results-card__website').text

					res = driver.find_element(By.CLASS_NAME, 'fane-results__summary').text.split(' ')[0]

					try:
						link = l.find_element(By.CLASS_NAME, 'fane-results-card__cta').get_attribute('href')
						##### NEW TAB
						driver.execute_script("window.open('');")
						driver.switch_to.window(driver.window_handles[1])
						driver.get(link)
						driver.implicitly_wait(60)
						time.sleep(1)

						sps = driver.find_elements(By.CLASS_NAME, 'nutritionist-details__experience-section')
						for sp in sps:
							if 'SPECIALTY' in sp.text:
								specialties = sp.text.replace('SPECIALTY\n', '').replace('SPECIALTY', '').replace('\n', ', ')

						driver.close()
						driver.switch_to.window(driver.window_handles[0])
						##### NEW TAB
					except Exception as e:
						pass

					append_list_as_row(filepathHeaderCSV, [name, office, city, phone, email, website, specialties])
					print(totPage+' - '+str(tot)+'/'+res)
					tot += 1
					time.sleep(1)

				nxt = driver.find_element(By.CLASS_NAME, 'fane-pager__page--next')
				if 'disabled' not in nxt.get_attribute('innerHTML'):
					nxt.find_element(By.TAG_NAME, 'button').click()
					time.sleep(7)
					nextPage = 0
				elif 'disabled' in nxt.get_attribute('innerHTML'):
					nextPage = 1
			except Exception:
				nextPage = 0
				time.sleep(5)
				print('Try again.')
	else:
		print('No Data')
		nextPage = 1

driver.quit()



























